# The following lines were added by Docker Desktop to add commands to your PATH.
export PATH="$PATH:/Users/im-ad/.docker/bin"
# End of Docker Desktop section.

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"

