---

- shell:
  - command: |
      sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    description: install oh-my-zsh
    stdout: true
    stderr: true

- git:
    "~/.oh-my-zsh/custom/plugins/kube-aliases":
      url: https://github.com/Dbz/kube-aliases.git
      description: omzsh kube-aliases

- create:
    ~/.shell:
      mode: 0700
    ~/Projects:
      mode: 0755
    ~/Projects/personal:
      mode: 0755
    ~/Projects/sandbox:
      mode: 0755

- link:
    ~/.zshrc:
      path: config/zshrc
      force: true
    ~/.shell/zshrc_aliases:
      path: config/zshrc_aliases
      force: true
    ~/.shell/zshrc_hashes:
      path: config/zshrc_hashes
      force: true
    ~/.shell/zshrc_path:
      path: config/zshrc_path
      force: true
    ~/.zprofile:
      path: config/zprofile
      force: true
    ~/.gitconfig:
      path: config/gitconfig
      force: true
    ~/.gitignore_global:
      path: config/gitignore_global
      force: true

  - shell:
     - command: touch ~/.shell/zshrc_local
       description: create zsh inclusion for locals
       stdout: true
       stderr: true

