# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# It's not necessary to copy all keys to your config.
# If the key is missing in your config, "default-config.toml" will serve as a fallback

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = [
  'exec-and-forget sketchybar',
  'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0',
  'exec-and-forget sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
]

# Notify Sketchybar about workspace change
exec-on-workspace-change = [
  '/bin/bash',
  '-c',
  'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
]

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
key-mapping.preset = 'qwerty'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = "move-mouse window-lazy-center"

[gaps]
inner.horizontal = 5
inner.vertical = 5
outer.left = 5
outer.bottom = 5
outer.top = [{ monitor.main = 12 }, { monitor.secondary = 45 }, 12]
outer.right = 5

[mode.main.binding]

# All possible modifiers: cmd, alt, ctrl, shift
# All possible commands: https://nikitabobko.github.io/AeroSpace/commands
# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
alt-ctrl-slash = 'layout tiles horizontal vertical'
alt-ctrl-comma = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-ctrl-h = 'focus left'
alt-ctrl-j = 'focus down'
alt-ctrl-k = 'focus up'
alt-ctrl-l = 'focus right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-ctrl-shift-h = 'move left'
alt-ctrl-shift-j = 'move down'
alt-ctrl-shift-k = 'move up'
alt-ctrl-shift-l = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-ctrl-minus = 'resize smart -50'
alt-ctrl-equal = 'resize smart +50'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
alt-ctrl-1 = 'workspace 1'
alt-ctrl-2 = 'workspace 2'
alt-ctrl-3 = 'workspace 3'
alt-ctrl-4 = 'workspace 4'
alt-ctrl-5 = 'workspace 5'
alt-ctrl-b = 'workspace B' # browser
alt-ctrl-c = 'workspace C' # chats
alt-ctrl-i = 'workspace I' # ide
alt-ctrl-m = 'workspace M' # music
alt-ctrl-n = 'workspace N' # notes
alt-ctrl-t = 'workspace T' # terminal

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-ctrl-shift-1 = 'move-node-to-workspace 1'
alt-ctrl-shift-2 = 'move-node-to-workspace 2'
alt-ctrl-shift-3 = 'move-node-to-workspace 3'
alt-ctrl-shift-4 = 'move-node-to-workspace 4'
alt-ctrl-shift-5 = 'move-node-to-workspace 5'
alt-ctrl-shift-b = 'move-node-to-workspace B'
alt-ctrl-shift-c = 'move-node-to-workspace C'
alt-ctrl-shift-i = 'move-node-to-workspace I'
alt-ctrl-shift-m = 'move-node-to-workspace M'
alt-ctrl-shift-n = 'move-node-to-workspace N'
alt-ctrl-shift-t = 'move-node-to-workspace T'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
alt-ctrl-tab = 'workspace-back-and-forth'
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
alt-ctrl-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# Application rearanging
[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = "move-node-to-workspace T"

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = "move-node-to-workspace M"

[[on-window-detected]]
if.app-id = 'md.obsidian'
run = "move-node-to-workspace N"

[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
run = "move-node-to-workspace B"

[[on-window-detected]]
if.app-name-regex-substring = 'telegram'
run = 'move-node-to-workspace C'

[[on-window-detected]]
if.app-name-regex-substring = 'finder'
run = 'layout floating'
