---
name: Lint YAML

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main, work, personal]
    paths:
      - "**.yml"
      - "**.yaml"
      - ".github/workflows/**.yml"
      - ".github/workflows/**.yaml"
  pull_request:
    branches: [main, work, personal]
    paths:
      - "**.yml"
      - "**.yaml"
      - ".github/workflows/**.yml"
      - ".github/workflows/**.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lintYaml:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Check YAML files with linter
        uses: ibiqlik/action-yamllint@v3
        with:
          # All files under base dir
          file_or_dir: "."
          yamllint_config_filepath: ".yamllint"
